version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=identy
    ports:
      - 5432:5432
  smart-park-identy-back:
    build: .
    environment:
      IDENTY_DATABASE_URI: postgresql://root:root@postgres:5432/identy
      IDENTY_SECRET: super_secret
      IDENTY_REFRESH_SECRET: refresh_super_secret
    ports:
      - 8080:3000